#!/bin/bash

site=`basename $PWD`

file=`ls -t1 site* | head -1`

if [ -z "$file" ]; then
    echo ERROR: no local file to restore
    exit
fi

echo "Ensuring user and database exists..."
$(dirname "$0")/mkdb $site
if [ $? -ne 0 ]; then
    exit 1
fi

echo "Restoring from local file $file..."

# Exec the Kickstart restoration from inside the Devilbox Docker PHP container
cd ~/Utveckling/devilbox
# Unpack
echo "Unpacking..."
docker compose exec --user devilbox php bash -lc "cd $site; rm -rf htdocs/*; php ../kickstart.php $file htdocs -silent"

# Create a restore configuration
echo "Creating restore configuration..."
docker compose exec --user devilbox php bash -lc "cd $site/htdocs/installation; php ./cli.php config:make"

# Tweak it
echo "Tweaking it..."
docker compose exec --user devilbox php bash -lc "sed -Ei 's/^(\s*)(dbname|dbuser|dbpass):.*/\1\2: $site/' $site/htdocs/installation/config.yml.php"
docker compose exec --user devilbox php bash -lc "sed -Ei 's/^(\s*)(dbhost):.*/\1\2: mysql/' $site/htdocs/installation/config.yml.php"

# Do the restore
docker compose exec --user devilbox php bash -lc "cd $site/htdocs/installation; php ./cli.php execute"

# Remove installation directory
echo "Removing installation directory..."
docker compose exec --user devilbox php bash -lc "rm -rf $site/htdocs/installation"
