#!/bin/bash

site=`basename $PWD`

file=`ls -t1 site* | head -1`

if [ -z "$file" ]; then
    echo ERROR: no local file to restore
    exit
fi

echo "Ensuring user and database exists..."
$(dirname "$0")/mkdb $site

echo "Restoring from local file $file..."

yamlfile="from-local.yaml"

echo "siteInfo:" > $yamlfile
echo "    package: " $file >> $yamlfile

cp $(dirname "$0")/CiviCRM4JoomlaFixer.php .

cat >> $yamlfile <<EOF
    absolutepath: /shared/httpd/$site/htdocs
    name: 'DEVILBOX : $site'
    deletePackage: false

databaseInfo:
    site:
       dbdriver: mysqli
       dbhost: mysql
       dbuser: $site
       dbpass: $site
       dbname: $site
       dbprefix: evc4_
       utf8mb4: true

handlers:
    - ./CiviCRM4JoomlaFixer.php
EOF

new_web_host=$(basename "$(pwd)")."localhost.tv"

# Copy the UNiTE script
cp `which unite` ..

# Exec the UNiTE restoration from inside the Devilbox Docker PHP container
cd ~/Utveckling/devilbox
docker compose exec --user devilbox php bash -lc "cd $site; rm -rf htdocs/*; NEW_WEB_HOST=$new_web_host ../unite restore $yamlfile"
