#!/bin/bash

$(dirname "$0")/restore-from-file

site=`basename $PWD`

new_web_host=$(basename "$(pwd)")."localhost.tv"

# Run the CiviCRM tweaking which needs to run inside the devilbox docker container
echo "Fixing CiviCRM configuration..."
cp $(dirname "$0")/CiviCRM4JoomlaFixer.php .
cd ~/Utveckling/devilbox
docker compose exec --user devilbox php bash -lc "cd $site; NEW_WEB_HOST=$new_web_host php ./CiviCRM4JoomlaFixer.php"
