#!/bin/bash
if [ -z "$DEVILBOX_HOME" ]; then
    echo "You need to have DEVILBOX_HOME set to the home directory of your Devilbox installation"
    exit 1
fi

site=`basename $PWD`

file=`ls -t1 site*.jpa | head -1`

if [ -z "$file" ]; then
    echo "ERROR: no local file to restore"
    exit 1
fi

if [ ! -f "kickstart.php" ]; then
    echo "ERROR: you need to have a 'kickstart.php' in this directory"
    exit 1
fi

echo "Ensuring user and database exists..."
$(dirname "$0")/mkdb $site
if [ $? -ne 0 ]; then
    exit 1
fi

echo "Restoring from local file $file..."

# Exec the Kickstart restoration from inside the Devilbox Docker PHP container
cd $DEVILBOX_HOME
# Unpack
echo "Unpacking..."
docker compose exec --user devilbox php bash -lc "cd $site; rm -rf htdocs/*; php kickstart.php $file htdocs -silent"

# If there is no `cli.php` in the installation directory, then it is old version of Akeeba
if [ ! -f "installation/cli.php" ]; then
   echo "Extracting an old version Akeeba backup, no cli. You need to browse to '/kickstart.php' to restore your site."
   exit 1
fi


# Create a restore configuration
echo "Creating restore configuration..."
docker compose exec --user devilbox php bash -lc "cd $site/htdocs/installation; php ./cli.php config:make"

# Tweak it
echo "Tweaking it..."
docker compose exec --user devilbox php bash -lc "sed -Ei 's/^(\s*)(dbname|dbuser|dbpass):.*/\1\2: $site/' $site/htdocs/installation/config.yml.php"
docker compose exec --user devilbox php bash -lc "sed -Ei 's/^(\s*)(dbhost):.*/\1\2: mysql/' $site/htdocs/installation/config.yml.php"
docker compose exec --user devilbox php bash -lc "sed -Ei 's/^(\s*)(sitename):.*/\1\2: $site/' $site/htdocs/installation/config.yml.php"

# Do the restore
docker compose exec --user devilbox php bash -lc "cd $site/htdocs/installation; php ./cli.php execute"

# Remove installation directory
echo "Removing installation directory..."
docker compose exec --user devilbox php bash -lc "rm -rf $site/htdocs/installation"
